services:
  postgres: 
    image: postgres:15.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_USER:?err}
    ports:
      - 5432:5432
    volumes:
      - ./docker-volumes/pgdata:/var/lib/postgresql/data